---
apiVersion: v1
kind: Pod
metadata:
  name: console
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: color-deployment
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: color-app
  template:
    metadata:
      labels:
        app: color-app
    spec:
      containers:
        - image: bedis9/colors
          imagePullPolicy: IfNotPresent
          name: color-app-server
          env:
            - name: COLOR
              value: cyan
          ports:
            - containerPort: 8080
      terminationGracePeriodSeconds: 30
  strategy:
    blueGreen:
      # activeService specifies the service to update with the new template hash at time of promotion.
      # This field is mandatory for the blueGreen update strategy.
      activeService: color-app-active
      # previewService specifies the service to update with the new template hash before promotion.
      # This allows the preview stack to be reachable without serving production traffic.
      # This field is optional.
      previewService: color-app-preview
      # autoPromotionEnabled disables automated promotion of the new stack by pausing the rollout
      # immediately before the promotion. If omitted, the default behavior is to promote the new
      # stack as soon as the ReplicaSet are completely ready/available.
      # Rollouts can be resumed using: `kubectl argo rollouts promote ROLLOUT`
      autoPromotionEnabled: false

---
apiVersion: v1
kind: Service
metadata:
  name: color-app-active
  namespace: colors
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: color-app

---
apiVersion: v1
kind: Service
metadata:
  name: color-app-preview
  namespace: colors
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: color-app

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: color-app-vs
  namespace: colors
spec:
  hosts:
  # - color-app.test.com
  - "*"
  gateways:
  - color-app-gateway
  http:
    - name: "color-app-vs-test"
      route:
        - destination:
            host: color-app-preview.colors.svc.cluster.local
            port:
              number: 80
      match:
        - headers:
            end-user:
              exact: "test"

    - name: "color-app-vs"
      route:
        - destination:
            host: color-app-active.colors.svc.cluster.local

---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: color-app-gateway
  namespace: colors
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      # - "color-app.test.com"
      - "*"